In [2]:
import numpy as np

In [67]:
N = 4
maze = np.random.randint(0,2,(N,N))
reward = -1
action_prob = 0.25
discount_factor = 1.0
theta = 0.0001
# next_state = [[-1, 1, 4, -1], [-1, 2, 5, 0], [-1, 3, 6, 1], [-1, -1, 7, 2], [0, 5, 8, -1], [1, 6, 9, 4], [2,7,10,5], [3,-1,11,6] ,[4, 9, 12, -1], [5, 10, 13, 8], [6, 11, 14, 9], [7, -1, 15, 10], [8, 13, -1, -1], [9, 14, -1, 12], [10, 15, -1, 13], [11, -1, -1, 14]]
# next_state = [[12, 1, 4, 3], [13, 2, 5, 0], [14, 3, 6, 1], [15, 0, 7, 2], [0, 5, 8, 7], [1, 6, 9, 4], [2,7,10,5], [3,4,11,6] ,[4, 9, 12, 11], [5, 10, 13, 8], [6, 11, 14, 9], [7, 8, 15, 10], [8, 13, 0, 15], [9, 14, 1, 12], [10, 15, 2, 13], [11, 12, 3, 14]]
# next_state = [[0, 0, 0, 0], [1, 2, 5, 0], [2, 3, 6, 1], [3, 3, 7, 2], [0, 5, 8, 4], [1, 6, 9, 4], [2, 7, 10, 5], [3, 7, 11, 6] ,[4, 9, 12, 8], [5, 10, 13, 8], [6, 11, 14, 9], [7, 11, 15, 10], [8, 13, 12, 12], [9, 14, 13, 12], [10, 15, 14, 13], [15, 15, 15, 15]]
next_state = [[0, 0, 0, 0], [1, 2, 5, 0], [2, 3, 6, 1], [3, 3, 7, 2], [0, 5, 8, 4], [1, 6, 9, 4], [2, 7, 10, 5], [3, 7, 11, 6] ,[4, 9, 12, 8], [5, 10, 13, 8], [6, 11, 14, 9], [7, 11, 15, 10], [8, 13, 12, 12], [9, 14, 13, 12], [10, 15, 14, 13], [11, 15, 15, 14]]
nA = 4
nS = 16

In [72]:
def value_iteration():
    
    def one_step_lookahead(state, V):
        A = np.zeros(nA)
#         for a in range(nA):
#             for prob, next_state, reward, done in env.P[state][a]:
#                 A[a] += prob * (reward + discount_factor * V[next_state])
#         return A
        i = 0
        for a in range(nA):
            nxt = next_state[state][a]
            A[i] += (reward + discount_factor * V[nxt])
            i = i + 1
        return A
    
    V = np.zeros(nS)
    j = 0
    for j in range(2):
        # Stopping condition
        delta = 0
        
        # Update each state...
        for s in range(nS):
            # Do a one-step lookahead to find the best action
            A = one_step_lookahead(s, V)
            best_action_value = np.max(A)
            # Calculate delta across all states seen so far
            delta = max(delta, np.abs(best_action_value - V[s]))
            # Update the value function. Ref: Sutton book eq. 4.10. 
            V[s] = best_action_value        
        # Check if we can stop 
        if delta < theta:
            break
    
    # Create a deterministic policy using the optimal value function
    policy = np.zeros([nS, nA])
    for s in range(nS):
        # One step lookahead to find the best action for this state
        A = one_step_lookahead(s, V)
        best_action = np.argmax(A)
        # Always take the best action
        policy[s, best_action] = 1.0
    
    return policy, V

In [73]:
mpolicy, v = value_iteration()

print("Policy Probability Distribution:")
print(mpolicy)
print("")

print("Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(mpolicy, axis=1), (4, 4)))
print("")

print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape((4, 4)))
print("")

Policy Probability Distribution:
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]

Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Value Function:
[-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]

Reshaped Grid Value Function:
[[-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]
 [-2. -2. -2. -2.]]



In [6]:
# Test the value function
expected_v = np.array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 75.0%)
 x: array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1.])
 y: array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])

In [65]:
def value_iteration(V_s, theta=0.01, discount_rate=0.5):
    value_for_state_map = create_value_for_state_map() # 1.

    delta = 100 # 2.
    while not delta < theta: # 3.
        delta = 0 # 4.
        for state in range(1, 15): # 5.
            v = V_s[state] # 6. 
            
            totals = {} # 7.
            for action in ["N", "S", "E", "W"]:
                total = 0
                for state_prime in range(16):
                    total += value_for_state_map[(state_prime, -1, state, action)] * (-1 + discount_rate * V_s[state_prime])
                totals[action] = total
            
            V_s[state] = round(max(totals.values()), 4) # 8.
            delta = max(delta, abs(v - V_s[state])) # 9.
    return V_s # 10.


In [66]:
print(value_iteration())

TypeError: value_iteration() missing 1 required positional argument: 'V_s'