In [3]:
import numpy as np

In [19]:
N = 4
maze = np.random.randint(0,2,(N,N))
reward = -1
action_prob = 0.25
discount_factor = 1.0
theta = 0.0001
# next_state = [[-1, 1, 4, -1], [-1, 2, 5, 0], [-1, 3, 6, 1], [-1, -1, 7, 2], [0, 5, 8, -1], [1, 6, 9, 4], [2,7,10,5], [3,-1,11,6] ,[4, 9, 12, -1], [5, 10, 13, 8], [6, 11, 14, 9], [7, -1, 15, 10], [8, 13, -1, -1], [9, 14, -1, 12], [10, 15, -1, 13], [11, -1, -1, 14]]
# next_state = [[12, 1, 4, 3], [13, 2, 5, 0], [14, 3, 6, 1], [15, 0, 7, 2], [0, 5, 8, 7], [1, 6, 9, 4], [2,7,10,5], [3,4,11,6] ,[4, 9, 12, 11], [5, 10, 13, 8], [6, 11, 14, 9], [7, 8, 15, 10], [8, 13, 0, 15], [9, 14, 1, 12], [10, 15, 2, 13], [11, 12, 3, 14]]
# next_state = [[0, 0, 0, 0], [1, 2, 5, 0], [2, 3, 6, 1], [3, 3, 7, 2], [0, 5, 8, 4], [1, 6, 9, 4], [2, 7, 10, 5], [3, 7, 11, 6] ,[4, 9, 12, 8], [5, 10, 13, 8], [6, 11, 14, 9], [7, 11, 15, 10], [8, 13, 12, 12], [9, 14, 13, 12], [10, 15, 14, 13], [15, 15, 15, 15]]
next_state = [[0, 0, 0, 0], [1, 2, 5, 0], [2, 3, 6, 1], [3, 3, 7, 2], [0, 5, 8, 4], [1, 6, 9, 4], [2, 7, 10, 5], [3, 7, 11, 6] ,[4, 9, 12, 8], [5, 10, 13, 8], [6, 11, 14, 9], [7, 11, 15, 10], [8, 13, 12, 12], [9, 14, 13, 12], [10, 15, 14, 13], [11, 15, 15, 14]]
nA = 4
nS = 16

In [23]:
def one_step_lookahead(state, V):
        A = np.zeros(nA)
        i=0
        for a in range(4):
            nxt = next_state[state][a]
            A[i] += (reward + discount_factor * V[nxt])
            i = i+1
        return A

In [24]:
def value_iteration():
    
    V_old = np.zeros(nS)
    V_new = np.zeros(nS)
    while True:
        # Stopping condition
        delta = 0
        V_old = V_new.copy()
        # Update each state...
        for s in range(1, nS):
            # Do a one-step lookahead to find the best action
            A = one_step_lookahead(s, V_old)
            best_action_value = np.max(A)
            # Calculate delta across all states seen so far
            delta = max(delta, np.abs(best_action_value - V_old[s]))
            # Update the value function. Ref: Sutton book eq. 4.10. 
            V_new[s] = best_action_value    
        print(V_new)
        # Check if we can stop 
        if delta < theta:
            break
    
    # Create a deterministic policy using the optimal value function
    npolicy = np.zeros([nS, nA])
    for s in range(nS):
        # One step lookahead to find the best action for this state
        A = one_step_lookahead(s, V_new)
        best_action = np.argmax(A)
        # Always take the best action
        npolicy[s, best_action] = 1.0
    
    return npolicy, V_new

In [25]:
mpolicy, v = value_iteration()

print("Policy Probability Distribution:")
print(mpolicy)
print("")

print("Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(mpolicy, axis=1), (4, 4)))
print("")

print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape((4, 4)))
print("")

[ 0. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0. -1. -2. -2. -1. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
[ 0. -1. -2. -3. -1. -2. -3. -3. -2. -3. -3. -3. -3. -3. -3. -3.]
[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -4. -3. -4. -4. -4.]
[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -5. -3. -4. -5. -5.]
[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -5. -3. -4. -5. -6.]
[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -5. -3. -4. -5. -6.]
Policy Probability Distribution:
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]

Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):
[[0 3 3 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Value Function:
[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -5. -3. -4. -5. -6.]

Reshaped Grid Value Function:
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -4.]
 [-2. -3. -4

In [18]:
# Test the value function
print(v)
expected_v = np.array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

[ 0. -1. -2. -3. -1. -2. -3. -4. -2. -3. -4. -5. -3. -4. -5. -6.]


AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 37.5%)
 x: array([ 0., -1., -2., -3., -1., -2., -3., -4., -2., -3., -4., -5., -3.,
       -4., -5., -6.])
 y: array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])

In [ ]:
[[4, 9, 12, -2], [5, 10, 13, 8], [6, 11, 14, 9], [7, -1, 15, 10], [8, 13, -1, -1], [9, 14, -1, -1], [10, 15, -1, -1], [11, -1, -1, 14]]